### ISSUE TITLE
Broken link to Kojo in readme

### ISSUE THREAD

**Issue by bjornregnell** [litan/kojo-lib#10]
The link here:
https://github.com/litan/kojo-lib/blob/main/README.md?plain=1#L3
for some reason GitHub makes it into this;
https://github.com/litan/kojo-lib/blob/main/www.kojo.in
which gives a 404 error.
The URL needs to be absolute starting with https etc.
https://www.kojo.in/

**Comment by litan** [comment]
Good catch. Will fix.
