### ISSUE TITLE
the getting started shims should import builtins.*

### ISSUE THREAD

**Issue by bjornregnell** [litan/kojo-lib#8]
or else e.g. activateCanvas() is not visible...
Update the export in these files:
https://github.com/litan/kojo-lib/blob/main/getting-started/kojo-english.scala
https://github.com/litan/kojo-lib/blob/main/getting-started/kojo-swedish.scala

**Comment by bjornregnell** [comment]
I'll try to fix this soon and create a PR. A new github release of kojo-lib will be needed...

**Comment by bjornregnell** [comment]
or maybe it is enough to just update the existing release with the new getting-started-files?

**Comment by bjornregnell** [comment]
If just export builtins.* then
```
[error] ./kojolib.scala:5:17: Double definition:
[error] final def CanvasAPI: 
[error]   (net.kogics.kojo.English.CanvasAPI : => net.kogics.kojo.lite.DrawingCanvasAPI) in package object kojolib$package at line 4 and
[error] final def CanvasAPI: 
[error]   (builtins.CanvasAPI : => net.kogics.kojo.lite.DrawingCanvasAPI) in package object kojolib$package at line 5
[error] have the same type after erasure.
[error] 
[error] Consider adding a @targetName annotation to one of the conflicting definitions
[error] for disambiguation.
[error] export builtins.* 
[error]                 ^
Error compiling project (Scala 3.1.3, JVM)
```
so need to be
```
export builtins.{TurtleAPI => _, CanvasAPI => _, *} 

```

**Comment by bjornregnell** [comment]
PR ready: https://github.com/litan/kojo-lib/pull/9
ok by me if you for now just upload the changed files to the current release

**Comment by bjornregnell** [comment]
I just updated the PR with Scala 3-idiomatic as instead of => in export

**Comment by litan** [comment]
PR #9 merged. Changed files uploaded to the current release.

**Comment by bjornregnell** [comment]
Works like a charm :smile:

**Comment by litan** [comment]
Nicely done, Bjorn 👍😊
